name: ttboost_mobile
description: TTBoost Mobile (MVP)
publish_to: "none"
version: 0.1.11

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  web_socket_channel: ^2.4.5
  audioplayers: ^6.1.0
  http: ^1.2.2
  file_picker: ^8.0.7
  permission_handler: ^11.3.1
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  flutter_local_notifications: ^17.2.1+2
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  audio_session: ^0.1.19
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0
  url_launcher: ^6.3.1
  device_info_plus: ^10.1.2
  flutter_appauth: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - asset/nova_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "asset/nova_icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "asset/nova_icon.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "asset/nova_icon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "asset/nova_icon.png"
